In [7]:
import pandas as pd
import numpy as np

# train 80

In [8]:
file_names = ['data_lstm_mse_lag5.csv', 'data_lstm_mse_lag10.csv', 'data_lstm_mse_lag15.csv', 'data_lstm_mse_lag20.csv', 'data_lstm_mse_lag25.csv', 'data_lstm_mse_lag30.csv']
dfs = []

for file_name in file_names:
    df = pd.read_csv(file_name)
    dfs.append(df)

data = pd.concat(dfs)
data = data.fillna('')
data

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Drop out2,Third layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
0,5,Adam,32,,50,,,,,1,10,0.023304,0.086220,0.002084,0.045656
1,5,RMSprop,32,,50,,,,,1,10,0.026051,0.099542,0.002290,0.047852
2,5,Adam,64,,50,,,,,1,10,0.026095,0.104324,0.002440,0.049398
3,5,Adam,32,0.1,50,,,,,1,10,0.029741,0.122874,0.002586,0.050855
4,5,Adam,32,0.05,50,,,,,1,10,0.032410,0.109154,0.002627,0.051257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,30,Adam,32,0.001,50,,,,,1,10,0.022734,0.104956,0.002059,0.045379
8,30,Adam,32,0.005,100,,,,,1,10,0.020973,0.077932,0.002028,0.045035
9,30,Adam,32,0.005,100,0.1,,,,1,10,0.022035,0.089694,0.002071,0.045506
10,30,Adam,32,0.005,100,,50.0,,,1,10,0.025626,0.141868,0.002191,0.046804
11,30,Adam,32,0.005,50,,,,,1,20,0.022289,0.092985,0.002119,0.046036

In [9]:
data = data.drop(columns=["Drop out2","Third layer"])
data

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
0,5,Adam,32,,50,,,1,10,0.023304,0.086220,0.002084,0.045656
1,5,RMSprop,32,,50,,,1,10,0.026051,0.099542,0.002290,0.047852
2,5,Adam,64,,50,,,1,10,0.026095,0.104324,0.002440,0.049398
3,5,Adam,32,0.1,50,,,1,10,0.029741,0.122874,0.002586,0.050855
4,5,Adam,32,0.05,50,,,1,10,0.032410,0.109154,0.002627,0.051257
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,30,Adam,32,0.001,50,,,1,10,0.022734,0.104956,0.002059,0.045379
8,30,Adam,32,0.005,100,,,1,10,0.020973,0.077932,0.002028,0.045035
9,30,Adam,32,0.005,100,0.1,,1,10,0.022035,0.089694,0.002071,0.045506
10,30,Adam,32,0.005,100,,50.0,1,10,0.025626,0.141868,0.002191,0.046804
11,30,Adam,32,0.005,50,,,1,20,0.022289,0.092985,0.002119,0.046036

## MAE

In [10]:
mae_lstm = data.groupby(['Lags'])['MAE error'].transform(min) == data['MAE error']
data[mae_lstm]

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
11,5,Adam,32,,100,,,1,20,0.020476,0.074577,0.002057,0.045356
8,10,Adam,32,,100,,,1,10,0.020330,0.077081,0.002003,0.044754
9,15,Adam,32,0.005,50,0.1,,1,10,0.020882,0.081045,0.002047,0.045248
6,20,Adam,32,0.005,50,,,1,10,0.020603,0.075586,0.002082,0.045629
3,25,Adam,32,0.1,50,,,1,10,0.020791,0.078015,0.002096,0.045784
8,30,Adam,32,0.005,100,,,1,10,0.020973,0.077932,0.002028,0.045035

In [11]:
data80 = data[mae_lstm]
data80.to_csv('data_error.csv',index=False)

In [12]:
data1 = data[mae_lstm]
data1 = data1['MAE error'].mean()
print('Average MAE : %.5f' %data1)

Average MAE : 0.02068

In [13]:
datamae = data[mae_lstm]
datamae = datamae.drop(columns=["MAPE error","MSE error","RMSE error"])
datamae

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error
11,5,Adam,32,,100,,,1,20,0.020476
8,10,Adam,32,,100,,,1,10,0.020330
9,15,Adam,32,0.005,50,0.1,,1,10,0.020882
6,20,Adam,32,0.005,50,,,1,10,0.020603
3,25,Adam,32,0.1,50,,,1,10,0.020791
8,30,Adam,32,0.005,100,,,1,10,0.020973

----

## MAPE

In [14]:
mape_lstm = data.groupby(['Lags'])['MAPE error'].transform(min) == data['MAPE error']
data[mape_lstm]

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
11,5,Adam,32,,100,,,1,20,0.020476,0.074577,0.002057,0.045356
11,10,Adam,32,,50,,,1,20,0.020381,0.074959,0.002049,0.045265
10,15,Adam,32,0.005,50,0.1,50.0,1,10,0.021240,0.080831,0.002124,0.046085
6,20,Adam,32,0.005,50,,,1,10,0.020603,0.075586,0.002082,0.045629
3,25,Adam,32,0.1,50,,,1,10,0.020791,0.078015,0.002096,0.045784
8,30,Adam,32,0.005,100,,,1,10,0.020973,0.077932,0.002028,0.045035

In [15]:
data2 = data[mape_lstm]
data2 = data2['MAPE error'].mean()
print('Average MAPE : %.5f' %data2)

Average MAPE : 0.07698

In [16]:
datamape = data[mape_lstm]
datamape = datamape.drop(columns=["MAE error","MSE error","RMSE error"])
datamape

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAPE error
11,5,Adam,32,,100,,,1,20,0.074577
11,10,Adam,32,,50,,,1,20,0.074959
10,15,Adam,32,0.005,50,0.1,50.0,1,10,0.080831
6,20,Adam,32,0.005,50,,,1,10,0.075586
3,25,Adam,32,0.1,50,,,1,10,0.078015
8,30,Adam,32,0.005,100,,,1,10,0.077932

In [17]:
datamape.to_csv('data_error.csv',index=False)

----

## MSE

In [18]:
mse_lstm = data.groupby(['Lags'])['MSE error'].transform(min) == data['MSE error']
data[mse_lstm]

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
8,5,Adam,32,,100,,,1,10,0.022172,0.078861,0.002032,0.045083
0,10,Adam,32,,50,,,1,10,0.020345,0.075310,0.001980,0.044498
0,15,Adam,32,,50,,,1,10,0.021963,0.086015,0.002031,0.045063
0,20,Adam,32,,50,,,1,10,0.020944,0.077680,0.001977,0.044458
0,25,Adam,32,,50,,,1,10,0.021512,0.085131,0.002007,0.044801
8,30,Adam,32,0.005,100,,,1,10,0.020973,0.077932,0.002028,0.045035

In [19]:
data3 = data[mse_lstm]
data3 = data3['MSE error'].mean()
print('Average MSE : %.5f' %data3)

Average MSE : 0.00201

In [20]:
datamse = data[mse_lstm]
datamse = datamse.drop(columns=["MAPE error","MAE error","RMSE error"])
datamse

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MSE error
8,5,Adam,32,,100,,,1,10,0.002032
0,10,Adam,32,,50,,,1,10,0.001980
0,15,Adam,32,,50,,,1,10,0.002031
0,20,Adam,32,,50,,,1,10,0.001977
0,25,Adam,32,,50,,,1,10,0.002007
8,30,Adam,32,0.005,100,,,1,10,0.002028

----

## RMSE

In [21]:
rmse_lstm = data.groupby(['Lags'])['RMSE error'].transform(min) == data['RMSE error']
data[rmse_lstm]

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
8,5,Adam,32,,100,,,1,10,0.022172,0.078861,0.002032,0.045083
0,10,Adam,32,,50,,,1,10,0.020345,0.075310,0.001980,0.044498
0,15,Adam,32,,50,,,1,10,0.021963,0.086015,0.002031,0.045063
0,20,Adam,32,,50,,,1,10,0.020944,0.077680,0.001977,0.044458
0,25,Adam,32,,50,,,1,10,0.021512,0.085131,0.002007,0.044801
8,30,Adam,32,0.005,100,,,1,10,0.020973,0.077932,0.002028,0.045035

In [22]:
data4 = data[rmse_lstm]
data4 = data4['RMSE error'].mean()
print('Average RMSE : %.5f' %data4)

Average RMSE : 0.04482

In [23]:
datarmse = data[rmse_lstm]
datarmse = datarmse.drop(columns=["MAPE error","MAE error","MSE error"])
datarmse

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,RMSE error
8,5,Adam,32,,100,,,1,10,0.045083
0,10,Adam,32,,50,,,1,10,0.044498
0,15,Adam,32,,50,,,1,10,0.045063
0,20,Adam,32,,50,,,1,10,0.044458
0,25,Adam,32,,50,,,1,10,0.044801
8,30,Adam,32,0.005,100,,,1,10,0.045035

----

# last day

In [24]:
file_names1 = ['data_last_day_lag5.csv', 'data_last_day_lag10.csv', 'data_last_day_lag15.csv', 'data_last_day_lag20.csv', 'data_last_day_lag25.csv', 'data_last_day_lag30.csv']
dfs1 = []

for file_name1 in file_names1:
    df1 = pd.read_csv(file_name1)
    dfs1.append(df1)

data5 = pd.concat(dfs1)
data5 = data5.fillna('')
data5

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Drop out2,Third layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
0,5,Adam,32,,50,,,,,1,10,0.011943,0.057024,0.001834,0.042828
1,5,RMSprop,32,,50,,,,,1,10,0.014134,0.061505,0.001822,0.042686
2,5,Adam,64,,50,,,,,1,10,0.016937,0.082864,0.002659,0.051570
3,5,Adam,32,0.1,50,,,,,1,10,0.019179,0.106886,0.002075,0.045556
4,5,Adam,32,0.05,50,,,,,1,10,0.020574,0.104792,0.001988,0.044590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,30,Adam,32,0.05,100,,,,,1,10,0.293096,1.726908,0.090901,0.301498
9,30,Adam,32,0.05,50,0.1,,,,1,10,0.030170,0.171165,0.003010,0.054864
10,30,Adam,32,0.05,50,,50.0,,,1,10,0.014864,0.070726,0.001857,0.043098
11,30,Adam,32,0.05,50,,,,,1,20,0.010618,0.051346,0.001831,0.042792
12,30,Adam,32,0.05,50,,,,,1,30,0.018310,0.088785,0.001895,0.043537

In [25]:
data5 = data5.drop(columns=["Drop out2","Third layer"])
data5

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
0,5,Adam,32,,50,,,1,10,0.011943,0.057024,0.001834,0.042828
1,5,RMSprop,32,,50,,,1,10,0.014134,0.061505,0.001822,0.042686
2,5,Adam,64,,50,,,1,10,0.016937,0.082864,0.002659,0.051570
3,5,Adam,32,0.1,50,,,1,10,0.019179,0.106886,0.002075,0.045556
4,5,Adam,32,0.05,50,,,1,10,0.020574,0.104792,0.001988,0.044590
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,30,Adam,32,0.05,100,,,1,10,0.293096,1.726908,0.090901,0.301498
9,30,Adam,32,0.05,50,0.1,,1,10,0.030170,0.171165,0.003010,0.054864
10,30,Adam,32,0.05,50,,50.0,1,10,0.014864,0.070726,0.001857,0.043098
11,30,Adam,32,0.05,50,,,1,20,0.010618,0.051346,0.001831,0.042792
12,30,Adam,32,0.05,50,,,1,30,0.018310,0.088785,0.001895,0.043537

## MAE

In [26]:
mae_lstm1 = data5.groupby(['Lags'])['MAE error'].transform(min) == data5['MAE error']
data5[mae_lstm1]

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
6,5,Adam,32,0.005,50,,,1,10,0.010836,0.051084,0.001823,0.042695
9,10,Adam,32,0.005,50,0.1,,1,10,0.011366,0.053539,0.001819,0.042652
10,15,Adam,32,0.005,50,,50.0,1,10,0.010689,0.052357,0.001894,0.043518
10,20,Adam,32,0.005,50,,50.0,1,10,0.010519,0.051351,0.001876,0.043318
8,25,Adam,32,,100,,,1,10,0.011594,0.055983,0.001813,0.042577
11,30,Adam,32,0.05,50,,,1,20,0.010618,0.051346,0.001831,0.042792

In [27]:
data6 = data5[mae_lstm1]
data6 = data6['MAE error'].mean()
print('Average MAE : %.5f' %data6)

Average MAE : 0.01094

In [28]:
datamae1 = data5[mae_lstm1]
datamae1 = datamae1.drop(columns=["MAPE error","MSE error","RMSE error"])
datamae1

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error
6,5,Adam,32,0.005,50,,,1,10,0.010836
9,10,Adam,32,0.005,50,0.1,,1,10,0.011366
10,15,Adam,32,0.005,50,,50.0,1,10,0.010689
10,20,Adam,32,0.005,50,,50.0,1,10,0.010519
8,25,Adam,32,,100,,,1,10,0.011594
11,30,Adam,32,0.05,50,,,1,20,0.010618

----

## MAPE

In [29]:
mape_lstm1 = data5.groupby(['Lags'])['MAPE error'].transform(min) == data5['MAPE error']
data5[mape_lstm1]

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
6,5,Adam,32,0.005,50,,,1,10,0.010836,0.051084,0.001823,0.042695
6,10,Adam,32,0.005,50,,,1,10,0.011539,0.053332,0.001807,0.042510
6,15,Adam,32,0.005,50,,,1,10,0.010777,0.051141,0.001808,0.042519
6,20,Adam,32,0.005,50,,,1,10,0.010740,0.051085,0.001817,0.042621
11,25,Adam,32,,100,,,1,20,0.011638,0.054141,0.001805,0.042484
11,30,Adam,32,0.05,50,,,1,20,0.010618,0.051346,0.001831,0.042792

In [30]:
data7 = data5[mape_lstm1]
data7 = data7['MAPE error'].mean()
print('Average MAPE : %.5f' %data7)

Average MAPE : 0.05202

In [31]:
datamape1 = data5[mape_lstm1]
datamape1 = datamape1.drop(columns=["MAE error","MSE error","RMSE error"])
datamape1

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAPE error
6,5,Adam,32,0.005,50,,,1,10,0.051084
6,10,Adam,32,0.005,50,,,1,10,0.053332
6,15,Adam,32,0.005,50,,,1,10,0.051141
6,20,Adam,32,0.005,50,,,1,10,0.051085
11,25,Adam,32,,100,,,1,20,0.054141
11,30,Adam,32,0.05,50,,,1,20,0.051346

In [ ]:
datamape1.to_csv('data_error1.csv',index=False)

----

## MSE

In [32]:
mse_lstm1 = data5.groupby(['Lags'])['MSE error'].transform(min) == data5['MSE error']
data5[mse_lstm1]

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
1,5,RMSprop,32,,50,,,1,10,0.014134,0.061505,0.001822,0.042686
5,10,Adam,32,0.01,50,,,1,10,0.013826,0.067467,0.001801,0.042441
7,10,Adam,32,0.001,50,,,1,10,0.013826,0.067467,0.001801,0.042441
6,15,Adam,32,0.005,50,,,1,10,0.010777,0.051141,0.001808,0.042519
3,20,Adam,32,0.1,50,,,1,10,0.012270,0.058780,0.001795,0.042368
11,25,Adam,32,,100,,,1,20,0.011638,0.054141,0.001805,0.042484
11,30,Adam,32,0.05,50,,,1,20,0.010618,0.051346,0.001831,0.042792

In [33]:
data8 = data5[mse_lstm1]
data8 = data8['MSE error'].mean()
print('Average MSE : %.5f' %data8)

Average MSE : 0.00181

In [34]:
datamse1 = data5[mse_lstm1]
datamse1 = datamse1.drop(columns=["MAPE error","MAE error","RMSE error"])
datamse1

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MSE error
1,5,RMSprop,32,,50,,,1,10,0.001822
5,10,Adam,32,0.01,50,,,1,10,0.001801
7,10,Adam,32,0.001,50,,,1,10,0.001801
6,15,Adam,32,0.005,50,,,1,10,0.001808
3,20,Adam,32,0.1,50,,,1,10,0.001795
11,25,Adam,32,,100,,,1,20,0.001805
11,30,Adam,32,0.05,50,,,1,20,0.001831

----

## RMSE

In [35]:
rmse_lstm1 = data5.groupby(['Lags'])['RMSE error'].transform(min) == data5['RMSE error']
data5[rmse_lstm1]

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,MAE error,MAPE error,MSE error,RMSE error
1,5,RMSprop,32,,50,,,1,10,0.014134,0.061505,0.001822,0.042686
5,10,Adam,32,0.01,50,,,1,10,0.013826,0.067467,0.001801,0.042441
7,10,Adam,32,0.001,50,,,1,10,0.013826,0.067467,0.001801,0.042441
6,15,Adam,32,0.005,50,,,1,10,0.010777,0.051141,0.001808,0.042519
3,20,Adam,32,0.1,50,,,1,10,0.012270,0.058780,0.001795,0.042368
11,25,Adam,32,,100,,,1,20,0.011638,0.054141,0.001805,0.042484
11,30,Adam,32,0.05,50,,,1,20,0.010618,0.051346,0.001831,0.042792

In [36]:
data9 = data5[rmse_lstm1]
data9 = data9['RMSE error'].mean()
print('Average RMSE : %.5f' %data9)

Average RMSE : 0.04253

In [37]:
datarmse1 = data5[rmse_lstm1]
datarmse1 = datarmse1.drop(columns=["MAPE error","MAE error","MSE error"])
datarmse1

,Lags,Optimizer,Batch_size,Learning rate,Frist layer,Drop out,Second layer,Output layer,Epochs,RMSE error
1,5,RMSprop,32,,50,,,1,10,0.042686
5,10,Adam,32,0.01,50,,,1,10,0.042441
7,10,Adam,32,0.001,50,,,1,10,0.042441
6,15,Adam,32,0.005,50,,,1,10,0.042519
3,20,Adam,32,0.1,50,,,1,10,0.042368
11,25,Adam,32,,100,,,1,20,0.042484
11,30,Adam,32,0.05,50,,,1,20,0.042792

----